name: Application CI
on: [push, pull_request]

defaults:
  run:
    working-directory: front_end
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install NPM dependencies, build and test
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
